server:
  port: 80

#### rabbitmq配置
spring:
  rabbitmq:
    username: boot
    password: 123456
    addresses: 127.0.0.1
    host: 5672
    virtual-host: /boot
    listener:
      simple:
       retry:
         #### 开启消费者(程序出现异常的情况下)进行重试
         enabled: true
         #### 最大重试次数
         max-attempts: 5
         #### 重试间隔次数
         initial-interval: 3000
         #### 应用于上一重试间隔的乘数
         multiplier: 1
         #### 最大重试时间间隔
         max-interval: 30000
      #### 开启手动应答模式
       acknowledge-mode: manual
    #消息发送确认回调
#    publisher-confirms: true
#    publisher-returns: true

