spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_activiti?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 模板引擎
  thymeleaf:
    cache: false
  # 不自动检查resources/bpmn目录
  activiti:
    check-process-definitions: false
  devtools:
    restart:
       enabled: false

#mybatis:
#  # xml文件路径
#  mapper-locations: classpath:mybatis/**/*Mapper.xml
#  # 驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    com.activiti.demo: debug

