server:
  port: 8081

##redis数据库
spring:
   redis:
     # Redis服务器地址
     host: 47.102.115.140
     # Redis服务器连接端口
     port: 6379
     # Redis服务器连接密码（默认为空）
     password:
     # 所需要使用的库(0-15)
     database: 1
     # 连接超时时间（毫秒）
     timeout: 10000
     jedis:
       pool:
         # 连接池中的最大空闲连接
         max-idle: 8
         # 连接池中的最小空闲连接
         min-idle: 10
         # 连接池最大连接数（使用负值表示没有限制）
         max-active: 100
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1


